import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

// app/layout.tsx
import { Instrument_Sans, Figtree, Public_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import { GeistSans } from 'geist/font/sans'

const instrumentSans = Instrument_Sans({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--font-instrument-sans',
})

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-figtree',
})

const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-public-sans',
})
// end of my fonts setup


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${instrumentSans.variable} ${figtree.variable} ${publicSans.variable} ${GeistSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
